stickers/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from stickers import views
from stickers.decorators import redirect_if_logged_in


app_name = 'stickers'

urlpatterns = [
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^login/$',
        redirect_if_logged_in(auth_views.login),
        {'template_name': 'stickers/index.html'},
        name='login'
    ),
    url(
        r'^logout/$',
        views.logout_view,
        name='logout'
    ),
    url(
        r'^register/$',
        redirect_if_logged_in(views.user_create),
        name='register'
    ),
    url(
        r'^create/$',
        views.sticker_create,
        name='create'
    ),
    url(
        r'^delete/(?P<pk>[0-9]+)/$',
        views.StickerDelete.as_view(),
        name='delete'
    ),
]

sticky/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('stickers.urls')),
    url(r'^admin/', admin.site.urls),
]

stickers/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


class UserManager(BaseUserManager):

    def create_user(self, email, username, password):

        if not email or not username or not password:
            raise ValueError(
                'User must have a valid email, username and email.'
            )

        user = self.model(
            email=UserManager.normalize_email(email),
            username=username
        )
        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, email, username, password):

        user = self.create_user(
            email,
            username,
            password
        )
        user.is_staff = True
        user.save(using=self._db)
        return user


@python_2_unicode_compatible
class User(AbstractBaseUser):

    email = models.EmailField(
        verbose_name='email',
        max_length=254,
        unique=True,
        db_index=True
    )
    username = models.CharField(
        verbose_name='username',
        max_length=30,
        unique=True
    )
    date_joined = models.DateTimeField(
        verbose_name='date joined',
        auto_now_add=True,
        editable=False
    )
    is_staff = models.BooleanField(
        default=False
    )

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        get_latest_by = 'date_joined'
        ordering = ['-date_joined', ]

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_short_name(self):
        return self

    def get_full_name(self):
        return self.get_short_name()

    def __str__(self):
        return self.username


class Sticker(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    color = models.CharField(max_length=50, default='lightgrey')
    date = models.DateTimeField(verbose_name='date created', auto_now_add=True)
    description = models.TextField()

    def __unicode__(self):
        return self.title

stickers/views.py
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import logout
from django.utils.decorators import method_decorator

from stickers.models import User, Sticker


class IndexView(generic.ListView):
    template_name = 'stickers/index.html'
    context_object_name = 'latest_stickers'

    def get_queryset(self):
        if self.request.user.is_authenticated():
            return Sticker.objects.filter(
                author=self.request.user).order_by('-date')[:50]
        return []


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('stickers:index'))


def user_create(request):
    User.objects.create_user(
        username=request.POST.get('username'),
        password=request.POST.get('password'),
        email=request.POST.get('email'),
    )
    return HttpResponseRedirect(reverse('stickers:index'))


@login_required
def sticker_create(request):
    sticker = Sticker.objects.create(
        author=request.user,
        title=request.POST.get('title'),
        description=request.POST.get('description'),
        color=request.POST.get('color')
    )
    if sticker.pk is not None:
        return HttpResponse(sticker.pk)
    return Http404


class StickerDelete(DeleteView):
    model = Sticker
    success_url = reverse_lazy('stickers:index')

    @method_decorator(login_required)
    def dispatch(self,  request, *args, **kwargs):
        return super(StickerDelete, self).dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super(StickerDelete, self).get_object(queryset)

        if obj.author != self.request.user:
            raise Http404

        return obj

stickers/templates/base.html
{% load staticfiles %}
{% spaceless %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" >
        
        <title>Sticky</title>
        
        <link rel="icon" href="{% static 'stickers/img/favicon.png' %}"> 
        <link rel="stylesheet" href="{% static 'stickers/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'stickers/css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'stickers/css/app.css' %}">
    </head>

    <body>
        <section class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a href="{% url 'stickers:index' %}" class="navbar-brand" title="Sticky">
                        <img src="{% static 'stickers/img/favicon.png' %}" alt="Sticky">
                    </a>
                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse" id="navbar-main">
                    <ul class="nav navbar-nav">
                        {% if user.is_authenticated %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-create dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-thumb-tack"></i>
                                </a>
                                <ul class="dropdown-menu" style="min-width: 250px">
                                    <form onsubmit="Sticker.Ajax.create(event, this)" style="padding: 10px">
                                        <input class="form-control input-sm" min-length="2" placeholder="Title..." name="title" type="text" autocomplete="off">
                                        <textarea class="form-control input-sm" placeholder="Description..." name="description" type="text" autocomplete="off"></textarea>
                                        <input class="form-control input-sm" placeholder="Color..." name="color" type="text">
                                        <input type="submit" class="btn btn-primary btn-sm" value="Stick">
                                    </form>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    {{ user.username }} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-header">{{ user.email }}</li>
                                    <br>
                                    <li><a href="#" onclick="return Sticker.reset()">Reset</a></li>
                                    <li><a href="{% url 'stickers:logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        {% else %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Login <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <form class="login" onsubmit="Sticker.Ajax.login(event, this, '{% url 'stickers:login' %}', '{% url 'stickers:index' %}')" style="padding: 10px">
                                        <input class="form-control input-sm" placeholder="Username..." name="username" type="text">
                                        <input class="form-control input-sm" placeholder="Password..." name="password" type="password">
                                        <input type="submit" class="btn btn-primary btn-sm" value="Login">
                                    </form>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    Register <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <form onsubmit="Sticker.Ajax.register(event, this, '{% url 'stickers:index' %}')" style="padding: 10px">
                                        <input class="form-control input-sm" placeholder="Username..." name="username" type="text" autocomplete="off">
                                        <input class="form-control input-sm" placeholder="Email..."    name="email"    type="email" autocomplete="off">
                                        <input class="form-control input-sm" placeholder="Password..." name="password" type="password" autocomplete="off">
                                        <input type="submit" class="btn btn-success btn-sm" value="Register">
                                    </form>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </section>

        <section class="message-container">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li class="alert alert-{{ message.tags }}">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </section>

        <section class="page container-fluid">
            {% block content %}{% endblock content %}
        </section>

        <section>
            <script>
                django = {
                    'url_register': '{% url 'stickers:register' %}',
                    'url_login':    '{% url 'stickers:login' %}',
                    'url_create':   '{% url 'stickers:create' %}',
                    'url_delete':   '{% url 'stickers:delete' 0 %}',
                    'csrf_token': '{{ csrf_token }}',
                }
            </script>

            <script src="{% static 'stickers/js/jquery.js' %}"></script>
            <script src="{% static 'stickers/js/jquery-ui.js' %}"></script>
            <script src="{% static 'stickers/js/jquery-scroll.js' %}"></script>
            <script src="{% static 'stickers/js/bootstrap.js' %}"></script>
            <script src="{% static 'stickers/js/app.js' %}"></script>

            <audio volume="1"><source src="{% static 'stickers/aud/move.mp3' %}"  type="audio/mpeg"></audio>
            <audio volume="1"><source src="{% static 'stickers/aud/place.mp3' %}" type="audio/mpeg"></audio>
        </section>
    </body>
</html>
{% endspaceless %}

stickers/templates/stickers/include/authenticate.html
<div class="container">

    <div class="col-md-6">

        <div class="panel panel-primary">
            
            <div class="panel-heading" style="font-size: larger">Login</div>

            <div class="panel-body" style="padding: 3em">
                <form onsubmit="Sticker.Ajax.login(event, this, '{% url 'stickers:index' %}')" style="padding: 10px">
                    <input class="form-control" placeholder="Username..." name="username" type="text" autocomplete="off">
                    <input class="form-control" placeholder="Password..." name="password" type="password" autocomplete="off">
                    <input type="submit" class="btn btn-primary" value="Login">
                </form>
            </div>

        </div>

    </div>

    <div class="col-md-6">
        
        <div class="panel panel-success">
            
            <div class="panel-heading" style="font-size: larger">Register</div>

            <div class="panel-body" style="padding: 3em">
                <form onsubmit="Sticker.Ajax.register(event, this, '{% url 'stickers:index' %}')" style="padding: 10px">
                    <input class="form-control" placeholder="Username..." name="username" type="text"     autocomplete="off">
                    <input class="form-control" placeholder="Email..."    name="email"    type="email"    autocomplete="off">
                    <input class="form-control" placeholder="Password..." name="password" type="password" autocomplete="off">
                    <input type="submit" class="btn btn-success" value="Register">
                </form>
            </div>

        </div>

    </div>

</div>

stickers/templates/stickers/index.html
{% extends "base.html" %}

{% block content %}

    {% if user.is_authenticated %}

        {# Sticker list #}

        <div class="sticker-container" style="display: none">

            {% if latest_stickers %}

                {% for sticker in latest_stickers %}

                    <div class="sticker-outer">

                        <div class="sticker panel panel-primary"data-id="{{ sticker.id }}"data-color="{{ sticker.color }}"title="{{ sticker.date | timesince }} ago by {{ sticker.author.username }}" {% if not sticker.description %}no-description{% endif %} {% if not sticker.color %}no-color{% endif %}>

                            <div class="color" style="background: {{ sticker.color }}"></div>
                            
                            <div class="title panel-heading">
                                {{ sticker.title }}
                            </div>
                            
                            <div class="description panel-body">
                                {{ sticker.description | linebreaksbr }}
                            </div>

                        </div>

                    </div>

                {% endfor %}

            {% endif %}

        </div>

        {# No sticker message #}

        <div class="oh-no-stickers text-center" style="margin-top: 40px; display: none">
            <strong>No Stickers</strong>
            <h1 style="font-size: 10em">&#x1f60f;</h1>
        </div>

        {# Empty sticker to clone from #}

        <div class="sticker-empty sticker-outer">
            <div class="sticker panel panel-primary" data-id="0" no-description no-color>
                <div class="color"></div>
                <div class="title panel-heading"></div>
                <div class="description panel-body"></div>
            </div>
        </div>

    {% else %}

        {% include "stickers/include/authenticate.html" %}

    {% endif %}

{% endblock %}